-- AlterTable
ALTER TABLE "Shape" ADD COLUMN     "secondx" DOUBLE PRECISION,
ADD COLUMN     "secondy" DOUBLE PRECISION,
ADD COLUMN     "thirdX" DOUBLE PRECISION,
ADD COLUMN     "thirdY" DOUBLE PRECISION;
